// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/freestuff-feed/MobileFeed.tsx": () => import("../components/mockups/freestuff-feed/MobileFeed.tsx"),
  "./components/mockups/freestuff-feed/SidebarGrid.tsx": () => import("../components/mockups/freestuff-feed/SidebarGrid.tsx")
};
